"""PowerPoint presentation builder using python-pptx."""

from __future__ import annotations

import os
import uuid
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN


def _add_title_slide(prs: Presentation, title: str, subtitle: str) -> None:
    layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(layout)
    slide.shapes.title.text = title
    slide.placeholders[1].text = subtitle


def _add_content_slide(prs: Presentation, title: str, bullets: list[str]) -> None:
    layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(layout)
    slide.shapes.title.text = title
    body = slide.placeholders[1]
    tf = body.text_frame
    tf.clear()
    for i, bullet in enumerate(bullets):
        if i == 0:
            tf.paragraphs[0].text = bullet
        else:
            p = tf.add_paragraph()
            p.text = bullet


def _add_text_slide(prs: Presentation, title: str, body_text: str) -> None:
    layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(layout)
    slide.shapes.title.text = title
    slide.placeholders[1].text = body_text


def create_pptx(context: dict) -> str:
    """Create a PPTX file from aggregated agent outputs and return the file path."""
    prs = Presentation()

    # -- Slide 1: Title --
    customer = context.get("customerName", "Customer")
    _add_title_slide(
        prs,
        f"Azure Solution Proposal – {customer}",
        "Generated by OneStopAgent",
    )

    # -- Slide 2: Requirements --
    description = context.get("description", "No description provided.")
    _add_text_slide(prs, "Customer Requirements", description[:2000])

    # -- Slide 3: Architecture overview --
    arch = context.get("architecture", {})
    narrative = arch.get("narrative", "Architecture not yet generated.")
    _add_text_slide(prs, "Architecture Overview", narrative)

    # -- Slide 4: Architecture components --
    components = arch.get("components", [])
    if components:
        bullets = [
            f"{c.get('name', 'Component')}: {c.get('azureService', 'TBD')} – {c.get('purpose', '')}"
            for c in components[:12]
        ]
        _add_content_slide(prs, "Architecture Components", bullets)

    # -- Slide 5: Azure services --
    svc_data = context.get("serviceSelections", {})
    selections = svc_data.get("selections", [])
    if selections:
        bullets = [
            f"{s['serviceName']} ({s.get('sku', 'N/A')}) – {s.get('componentName', '')}"
            for s in selections[:12]
        ]
        _add_content_slide(prs, "Selected Azure Services", bullets)

    # -- Slide 6: Cost estimate --
    cost = context.get("costEstimate", {})
    estimate = cost.get("estimate", cost)
    items = estimate.get("items", [])
    total_m = estimate.get("totalMonthly", 0)
    total_a = estimate.get("totalAnnual", 0)
    if items:
        bullets = [f"{it['serviceName']} ({it.get('sku', '')}): ${it.get('monthlyCost', 0):,.2f}/mo" for it in items[:10]]
        bullets.append(f"Total: ${total_m:,.2f}/month  |  ${total_a:,.2f}/year")
        _add_content_slide(prs, "Cost Estimate", bullets)
    else:
        _add_text_slide(prs, "Cost Estimate", f"Monthly: ${total_m:,.2f}   Annual: ${total_a:,.2f}")

    # -- Slide 7: Business value --
    bv = context.get("businessValue", {})
    assessment = bv.get("assessment", bv)
    drivers = assessment.get("drivers", [])
    if drivers:
        bullets = [f"{d['name']}: {d.get('impact', '')}" for d in drivers]
        summary = assessment.get("executiveSummary", "")
        if summary:
            bullets.append(f"Summary: {summary[:300]}")
        _add_content_slide(prs, "Business Value & ROI", bullets)
    else:
        _add_text_slide(prs, "Business Value & ROI", assessment.get("executiveSummary", "Not yet assessed."))

    # -- Slide 8: Next steps --
    _add_content_slide(
        prs,
        "Next Steps",
        [
            "Review architecture and service selections",
            "Validate cost estimates with Azure Pricing Calculator",
            "Schedule deep-dive with Azure engineering team",
            "Begin proof-of-concept implementation",
            "Set up Azure governance and landing zone",
        ],
    )

    # Save
    out_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "output")
    os.makedirs(out_dir, exist_ok=True)
    filename = f"OneStopAgent-{customer.replace(' ', '_')}-{uuid.uuid4().hex[:8]}.pptx"
    filepath = os.path.join(out_dir, filename)
    prs.save(filepath)
    return filepath
