"""Presentation Agent — generates executive-ready PowerPoint deck."""
import json
from agents.llm import llm
from agents.state import AgentState
from services.presentation import create_pptx


class PresentationAgent:
    name = "Presentation"
    emoji = "📑"

    def run(self, state: AgentState) -> AgentState:
        # Step 1: Build slide data from state
        slides = self._build_slides(state)

        # Step 2: Use LLM to polish slide content
        polished = self._polish_with_llm(slides, state)

        # Step 3: Render to PPTX
        path = create_pptx(polished, state.customer_name or "Customer")
        state.presentation_path = path
        return state

    def _build_slides(self, state: AgentState) -> list[dict]:
        """Build raw slide data from state — 9 slides per FRD-05 §3.4."""
        slides = []
        customer = state.customer_name or "Customer"

        # Slide 1: Title (always)
        slides.append({
            "type": "title",
            "title": f"{customer} — Azure Solution Proposal",
            "subtitle": "Generated by OneStopAgent",
        })

        # Slide 2: Problem/Opportunity
        slides.append({
            "type": "content",
            "title": "Problem & Opportunity",
            "body": state.user_input,
            "notes": state.clarifications or "",
        })

        # Slide 3: Solution Overview
        if state.architecture:
            slides.append({
                "type": "content",
                "title": "Solution Overview",
                "body": state.architecture.get("narrative", ""),
                "based_on": state.architecture.get("basedOn", ""),
            })

        # Slide 4: Architecture (component table)
        if state.architecture.get("components"):
            slides.append({
                "type": "table",
                "title": "Architecture Components",
                "headers": ["Component", "Azure Service", "Description"],
                "rows": [
                    [c.get("name", ""), c.get("azureService", ""), c.get("description", "")]
                    for c in state.architecture["components"][:12]
                ],
            })

        # Slide 5: Azure Services
        if state.services.get("selections"):
            slides.append({
                "type": "table",
                "title": "Azure Services & SKUs",
                "headers": ["Service", "SKU", "Region"],
                "rows": [
                    [s.get("serviceName", ""), s.get("sku", ""), s.get("region", "")]
                    for s in state.services["selections"][:12]
                ],
            })

        # Slide 6: Cost Estimate
        if state.costs.get("estimate"):
            est = state.costs["estimate"]
            slides.append({
                "type": "table",
                "title": f"Cost Estimate — ${est.get('totalMonthly', 0):,.2f}/month",
                "headers": ["Service", "SKU", "Monthly Cost"],
                "rows": [
                    [i.get("serviceName", ""), i.get("sku", ""), f"${i.get('monthlyCost', 0):,.2f}"]
                    for i in est.get("items", [])[:15]
                ],
                "footer": f"Annual: ${est.get('totalAnnual', 0):,.2f} | Source: {est.get('pricingSource', 'N/A')}",
            })

        # Slide 7: Business Value
        if state.business_value.get("drivers"):
            drivers = state.business_value["drivers"]
            body_lines = []
            for d in drivers:
                line = f"• {d.get('name', '')}: {d.get('estimate', d.get('impact', ''))}"
                body_lines.append(line)
            slides.append({
                "type": "content",
                "title": "Business Value",
                "body": "\n".join(body_lines),
                "notes": state.business_value.get("executiveSummary", ""),
            })

        # Slide 8: ROI (NEW per FRD-05)
        if state.roi:
            roi = state.roi
            if roi.get("roi_percent") is not None:
                body = (
                    f"ROI: {roi['roi_percent']:.0f}%\n"
                    f"Payback: {roi.get('payback_months', 'N/A'):.1f} months\n\n"
                    f"Annual Azure cost: ${roi['annual_cost']:,.2f}\n"
                    f"Annual value: ${roi['annual_value']:,.2f}"
                )
                if roi.get("monetized_drivers"):
                    body += "\n\nMonetized value drivers:"
                    for d in roi["monetized_drivers"]:
                        body += f"\n• {d['name']}: ${d['annual_value']:,.2f}/year"
            else:
                body = "ROI could not be calculated quantitatively.\n\nQualitative benefits:"
                for b in roi.get("qualitative_benefits", []):
                    body += f"\n• {b}"
            slides.append({
                "type": "content",
                "title": "Return on Investment",
                "body": body,
            })

        # Slide 9: Next Steps (always)
        slides.append({
            "type": "content",
            "title": "Recommended Next Steps",
            "body": (
                "1. Schedule deep-dive architecture review\n"
                "2. Set up Azure subscription and landing zone\n"
                "3. Build proof-of-concept (4-6 weeks)\n"
                "4. Define success metrics and KPIs\n"
                "5. Plan phased rollout with pilot group"
            ),
        })

        return slides

    def _polish_with_llm(self, slides: list[dict], state: AgentState) -> list[dict]:
        """Use LLM to polish slide content for executive audience."""
        try:
            customer = state.customer_name or "Customer"
            prompt = (
                "Polish these presentation slides for an executive audience.\n"
                "For each slide, improve the language to be concise, professional, and impactful.\n"
                "Use bullet points, highlight key numbers, remove technical jargon.\n"
                f"Customer: {customer}\n\n"
                f"Slides: {json.dumps(slides, default=str)}\n\n"
                "Return the SAME JSON structure with improved \"body\" and \"notes\" text.\n"
                "Return ONLY valid JSON array."
            )

            response = llm.invoke([
                {
                    "role": "system",
                    "content": (
                        "You are a presentation content expert. Return ONLY valid JSON "
                        "array of slide objects. Keep the same structure, improve the text."
                    ),
                },
                {"role": "user", "content": prompt},
            ])

            text = response.content.strip()
            if text.startswith("```"):
                text = text.split("\n", 1)[1].rsplit("```", 1)[0].strip()

            polished = json.loads(text)
            if isinstance(polished, list) and len(polished) == len(slides):
                return polished
        except Exception:
            pass

        # Fallback: use raw slides
        return slides
